In [4]:
import pandas as pd
from os import listdir
from os.path import isfile, join
import ast

In [6]:
df = pd.read_csv("data/books_genres/sf_aliens.csv")

In [10]:
df["Subgenre"] = "aliens"

In [17]:
df.columns

Index(['Book_Title', 'Original_Book_Title', 'Author_Name', 'Edition_Language',
       'Rating_score', 'Rating_votes', 'Review_number', 'Book_Description',
       'Year_published', 'Genres', 'url', 'Subgenre'],
      dtype='str')

In [15]:
mypath = "data/books_genres"
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f)) and f.endswith(".csv")]

In [16]:
onlyfiles

['sf_alternate_history.csv',
 'sf_dystopia.csv',
 'sf_steampunk.csv',
 'sf_time_travel.csv',
 'sf_hard.csv',
 'sf_aliens.csv',
 'sf_space_opera.csv',
 'sf_cyberpunk.csv',
 'sf_military.csv',
 'sf_robots.csv',
 'sf_alternate_universe.csv',
 'sf_apocalyptic.csv']

In [19]:
columns = ['Book_Title', 'Original_Book_Title', 'Author_Name', 'Edition_Language',
       'Rating_score', 'Rating_votes', 'Review_number', 'Book_Description',
       'Year_published', 'Genres', 'url', 'Subgenre']

In [23]:
df = pd.DataFrame(columns=columns)
for file in onlyfiles:
    print(file)
    df_subgenre = pd.read_csv(join(mypath, file))
    subgenre = file[3:-4]
    df_subgenre["Subgenre"] = subgenre
    df = pd.concat([df, df_subgenre], ignore_index=True)
print(df.head())

sf_alternate_history.csv
sf_dystopia.csv
sf_steampunk.csv
sf_time_travel.csv
sf_hard.csv
sf_aliens.csv
sf_space_opera.csv
sf_cyberpunk.csv
sf_military.csv
sf_robots.csv
sf_alternate_universe.csv
sf_apocalyptic.csv
                      Book_Title            Original_Book_Title  \
0     The Man in the High Castle     The Man in the High Castle
1           His Majesty's Dragon           His Majesty's Dragon
2                      Leviathan                      Leviathan
3  Jonathan Strange & Mr Norrell  Jonathan Strange & Mr Norrell
4  The Yiddish Policemen's Union  The Yiddish Policemen's Union

        Author_Name Edition_Language Rating_score Rating_votes Review_number  \
0    Philip K. Dick          English         3.62       180593         11895
1       Naomi Novik          English         4.03        83308          6588
2  Scott Westerfeld          English          3.9        88293          7052
3    Susanna Clarke          English         3.82       206919         14397
4    Michael Chabon          English         3.71        70984          6992

                                    Book_Description Year_published  \
0  It's America in 1962. Slavery is legal once ag...           1962
1  Aerial combat brings a thrilling new dimension...           2006
2  Prince Aleksander, would-be heir to the Austro...           2009
3  Sophisticated, witty, and ingeniously convinci...           2004
4  For sixty years, Jewish refugees and their des...           2007

                                              Genres  \
0  {'Science Fiction': 4175, 'Fiction': 3446, 'Sc...
1  {'Fantasy': 7710, 'Fantasy (Dragons) ': 1350, ...
2  {'Science Fiction (Steampunk) ': 3334, 'Young ...
3  {'Fantasy': 11071, 'Fiction': 3752, 'Historica...
4  {'Fiction': 2240, 'Mystery': 919, 'Science Fic...

                                                 url           Subgenre
0  https://www.goodreads.com/book/show/216363.The...  alternate_history
1  https://www.goodreads.com/book/show/28876.His_...  alternate_history
2  https://www.goodreads.com/book/show/6050678-le...  alternate_history
3  https://www.goodreads.com/book/show/14201.Jona...  alternate_history
4  https://www.goodreads.com/book/show/16703.The_...  alternate_history

In [27]:
df = df.drop_duplicates(subset=["Book_Title", "Author_Name"], keep="first")
df.sort_values(by="Review_number", ascending=False)

,Book_Title,Original_Book_Title,Author_Name,Edition_Language,Rating_score,Rating_votes,Review_number,Book_Description,Year_published,Genres,url,Subgenre
289,The Hunger Games,The Hunger Games,Suzanne Collins,English,4.33,6572148,174079,"Could you survive on your own in the wild, wit...",2008,"{'Young Adult': 31089, 'Fiction': 17571, 'Scie...",https://www.goodreads.com/book/show/2767052-th...,alternate_history
12589,Harry Potter and the Sorcerer's Stone,Harry Potter and the Philosopher's Stone,J.K. Rowling,English,4.48,7336299,116268,Harry Potter's life is miserable. His parents ...,1997,"{'Fantasy': 63272, 'Fiction': 18715, 'Young Ad...",https://www.goodreads.com/book/show/3.Harry_Po...,alternate_universe
761,Divergent,Divergent,Veronica Roth,English,4.19,3008156,109103,"In Beatrice Prior's dystopian Chicago world, s...",2011,"{'Young Adult': 20861, 'Science Fiction (Dysto...",https://www.goodreads.com/book/show/13335037-d...,alternate_history
594,Mockingjay,Mockingjay,Suzanne Collins,English,4.0,2012173,101751,My name is Katniss Everdeen.Why am I not dead?...,2010,"{'Young Adult': 24917, 'Science Fiction (Dysto...",https://www.goodreads.com/book/show/7260188-mo...,alternate_history
452,Catching Fire,Catching Fire,Suzanne Collins,English,4.29,2605868,97937,Sparks are igniting.Flames are spreading.And t...,2009,"{'Young Adult': 26370, 'Science Fiction (Dysto...",https://www.goodreads.com/book/show/6148028-ca...,alternate_history
...,...,...,...,...,...,...,...,...,...,...,...,...
12477,Engineward #3,B08D6W8Y5Z,George Mann,NaN,4.0,2,0,NaN,2020,{'None': 1000},https://www.goodreads.com/book/show/55448608-e...,robots
11939,Machine Man #1,English,Jack Kirby,English,3.5,6,0,"Machine Man #1, Marvel Comics",0,"{'Comics (Comic Book) ': 2, 'Science Fiction':...",https://www.goodreads.com/book/show/22240523-m...,robots
9812,Deep Space: The Interplanetary Supplement for ...,Deep Space: The Interplanetary Supplement for ...,Chris Young,NaN,3.75,12,0,NaN,1993,"{'Science Fiction (Cyberpunk) ': 4, 'Games (Ga...",https://www.goodreads.com/book/show/1836919.De...,cyberpunk
9813,Chromebook (Cyberpunk RPG,Chromebook (Cyberpunk RPG),Colin Fisk,English,3.66,29,0,Additional materials for Cyberpunk Role playin...,1991,"{'Games (Role Playing Games) ': 5, 'Science Fi...",https://www.goodreads.com/book/show/2308020.Ch...,cyberpunk
12349,The Unofficial Guide to LEGO MINDSTORMS Robots,The Unofficial Guide to LEGO MINDSTORMS Robots,Jonathan Knudsen,NaN,3.18,22,0,The LEGO® MINDSTORMS™ Robotics Invention Syste...,1999,"{'Reference': 3, 'Computer Science (Computers)...",https://www.goodreads.com/book/show/2825118-th...,robots

In [28]:
df.to_csv("data/scifi_books.csv", index=False)

In [49]:
genres = ast.literal_eval(df["Genres"][555])

In [50]:
summary = sum(genres.values())
for genre in genres:
    ratio = genres[genre] / summary
    print(f"{genre}: {ratio:.2%}")

Sequential Art (Comics) : 44.09%
Sequential Art (Graphic Novels) : 23.92%
Science Fiction: 12.68%
Science Fiction (Alternate History) : 6.34%
Fiction: 5.19%
Graphic Novels Comics: 2.88%
Comics (Comic Book) : 1.73%
Science Fiction (Alternate Universe) : 1.15%
Fantasy: 1.15%
War: 0.86%

In [56]:
for row in df.iterrows():
    genres = ast.literal_eval(row[1]["Genres"])
    summary = sum(genres.values())
    new_row = {}
    for genre in genres:
        ratio = genres[genre] / summary
        new_row[genre] = ratio
    row[1]["Genres"] = new_row
    print(row[1]["Genres"])

{'Science Fiction': 0.33932054616384916, 'Fiction': 0.28007152145643693, 'Science Fiction (Alternate History) ': 0.07916124837451236, 'Science Fiction (Dystopia) ': 0.07672301690507152, 'Classics': 0.07233420026007803, 'Historical (Historical Fiction) ': 0.05266579973992198, 'Fantasy': 0.03080299089726918, 'Science Fiction Fantasy': 0.026657997399219768, 'Novels': 0.02235045513654096, 'Speculative Fiction': 0.01991222366710013}
{'Fantasy': 0.5630203008616913, 'Fantasy (Dragons) ': 0.09858332116255294, 'Historical (Historical Fiction) ': 0.09361764276325397, 'Fiction': 0.07521542281291077, 'Historical': 0.04739301884036804, 'Science Fiction (Alternate History) ': 0.04301153789981014, 'Adventure': 0.02256462684387323, 'Historical Fiction (Historical Fantasy) ': 0.022053454067474807, 'Science Fiction Fantasy': 0.01971666423251059, 'War': 0.014824010515554258}
{'Science Fiction (Steampunk) ': 0.26725450901803605, 'Young Adult': 0.21330661322645292, 'Fantasy': 0.1474949899799599, 'Science Fiction': 0.10797595190380761, 'Historical (Historical Fiction) ': 0.08120240480961924, 'Fiction': 0.057154308617234466, 'Science Fiction (Alternate History) ': 0.036953907815631265, 'Adventure': 0.03655310621242485, 'Historical': 0.033587174348697395, 'Young Adult (Teen) ': 0.018517034068136273}
{'Fantasy': 0.5448863077074515, 'Fiction': 0.18466384486662074, 'Historical (Historical Fiction) ': 0.11029628900482331, 'Historical': 0.038734127374741606, 'Fantasy (Magic) ': 0.03514125406043902, 'Science Fiction Fantasy': 0.022295501525740724, 'Science Fiction (Alternate History) ': 0.020720543360566984, 'Audiobook': 0.016438625849000885, 'Adult': 0.013485579289300128, 'Magical Realism': 0.01333792696131509}
{'Fiction': 0.44409199048374304, 'Mystery': 0.18219666931007136, 'Science Fiction': 0.08822363203806503, 'Science Fiction (Alternate History) ': 0.0789056304520222, 'Mystery (Crime) ': 0.047581284694686754, 'Literature (Jewish) ': 0.045400475812846945, 'Fantasy': 0.03271213322759715, 'Novels': 0.030531324345757335, 'Literature': 0.02775574940523394, 'Literary Fiction': 0.02260111022997621}
{'Fiction': 0.29675425038639874, 'Historical (Historical Fiction) ': 0.19969088098918084, 'Thriller': 0.12117465224111283, 'Science Fiction (Alternate History) ': 0.11901081916537867, 'Mystery': 0.06491499227202473, 'Mystery (Crime) ': 0.05007727975270479, 'Science Fiction': 0.04420401854714065, 'Historical': 0.0401854714064915, 'Science Fiction (Dystopia) ': 0.03863987635239567, 'War': 0.02534775888717156}
{'Fantasy': 0.5365448504983389, 'Fantasy (Dragons) ': 0.10562015503875968, 'Historical (Historical Fiction) ': 0.09080841638981174, 'Fiction': 0.07212070874861573, 'Historical': 0.052740863787375414, 'Science Fiction (Alternate History) ': 0.052464008859357696, 'Adventure': 0.027131782945736434, 'Historical Fiction (Historical Fantasy) ': 0.026439645625692138, 'Science Fiction Fantasy': 0.020348837209302327, 'Young Adult': 0.015780730897009966}
{'Science Fiction': 0.4111587982832618, 'Fiction': 0.16967095851216024, 'Historical (Historical Fiction) ': 0.13190271816881258, 'Science Fiction (Alternate History) ': 0.10529327610872675, 'Historical': 0.044062947067238914, 'Adult': 0.03805436337625179, 'Space': 0.030042918454935622, 'Science Fiction Fantasy': 0.026609442060085836, 'Audiobook': 0.022317596566523604, 'Speculative Fiction': 0.02088698140200286}
{'Fiction': 0.2742607024661044, 'Historical (Historical Fiction) ': 0.1978755204441123, 'Science Fiction': 0.12378563040461193, 'Science Fiction (Time Travel) ': 0.09864417636383047, 'Fantasy': 0.07179459805700865, 'Horror': 0.06512223764278852, 'Thriller': 0.05796946727874453, 'Audiobook': 0.04206256005124373, 'Historical': 0.037365218319632756, 'Mystery': 0.031119888971922707}
{'Fiction': 0.2390873015873016, 'Science Fiction': 0.2197420634920635, 'Science Fiction (Alternate History) ': 0.1736111111111111, 'Historical (Historical Fiction) ': 0.13392857142857142, 'Fantasy': 0.12003968253968254, 'Speculative Fiction': 0.03125, 'Historical': 0.030753968253968252, 'Science Fiction Fantasy': 0.022817460317460316, 'Religion': 0.01636904761904762, 'Unfinished': 0.01240079365079365}
{'Science Fiction (Alternate History) ': 0.2304054054054054, 'Science Fiction': 0.225, 'Fiction': 0.13378378378378378, 'Science Fiction (Time Travel) ': 0.11756756756756757, 'Fantasy': 0.11756756756756757, 'Historical (Historical Fiction) ': 0.10337837837837838, 'Historical': 0.03310810810810811, 'War': 0.01418918918918919, 'Science Fiction Fantasy': 0.013513513513513514, 'War (Military Fiction) ': 0.011486486486486487}
{'Science Fiction (Alternate History) ': 0.27796901893287435, 'Science Fiction': 0.18502581755593803, 'Fiction': 0.1686746987951807, 'Historical (Historical Fiction) ': 0.14027538726333907, 'Science Fiction (Time Travel) ': 0.07487091222030981, 'Military History (Civil War) ': 0.04819277108433735, 'Fantasy': 0.04388984509466437, 'Historical': 0.024096385542168676, 'War': 0.02323580034423408, 'War (Military Fiction) ': 0.013769363166953529}
{'Fantasy': 0.3439111463704879, 'Fiction': 0.21182070606902023, 'Mystery': 0.15017850059500198, 'Humor': 0.07306624355414518, 'Science Fiction': 0.0697342324474415, 'Writing (Books About Books) ': 0.047758825862752874, 'Science Fiction (Time Travel) ': 0.03712812376041254, 'Science Fiction (Alternate History) ': 0.02491074970249901, 'Science Fiction Fantasy': 0.023086076953589846, 'Adult': 0.018405394684648947}
{'Fiction': 0.482630979498861, 'Historical (Historical Fiction) ': 0.17938496583143507, 'Science Fiction (Alternate History) ': 0.08798405466970387, 'Literature': 0.040148063781321186, 'Science Fiction': 0.03616173120728929, 'Literature (American) ': 0.03616173120728929, 'Novels': 0.03616173120728929, 'Politics': 0.03559225512528474, 'Literature (Jewish) ': 0.03416856492027335, 'Literary Fiction': 0.03160592255125285}
{'Fantasy': 0.5334507042253521, 'Fantasy (Dragons) ': 0.1079225352112676, 'Historical (Historical Fiction) ': 0.09066901408450705, 'Fiction': 0.07376760563380282, 'Science Fiction (Alternate History) ': 0.05440140845070422, 'Historical': 0.05088028169014085, 'Adventure': 0.027464788732394368, 'Historical Fiction (Historical Fantasy) ': 0.026056338028169014, 'Science Fiction Fantasy': 0.01971830985915493, 'Young Adult': 0.015669014084507042}
{'Fantasy': 0.5224428139835995, 'Fantasy (Dragons) ': 0.11523521795425119, 'Historical (Historical Fiction) ': 0.09128182995252482, 'Fiction': 0.073370738023306, 'Science Fiction (Alternate History) ': 0.06042296072507553, 'Historical': 0.057617608977125596, 'Historical Fiction (Historical Fantasy) ': 0.0256797583081571, 'Science Fiction Fantasy': 0.02028485110056107, 'Adventure': 0.018990073370738023, 'Audiobook': 0.0146741476046612}
{'Science Fiction (Steampunk) ': 0.30045871559633025, 'Young Adult': 0.20543905635648754, 'Fantasy': 0.12434469200524247, 'Science Fiction': 0.0982961992136304, 'Historical (Historical Fiction) ': 0.07617955439056356, 'Fiction': 0.05520969855832241, 'Science Fiction (Alternate History) ': 0.04439711664482307, 'Adventure': 0.04128440366972477, 'Historical': 0.03505897771952818, 'Young Adult (Teen) ': 0.019331585845347315}
{'Science Fiction (Steampunk) ': 0.41676384839650144, 'Fantasy': 0.13279883381924198, 'Science Fiction': 0.12128279883381925, 'Fiction': 0.09635568513119533, 'Horror (Zombies) ': 0.07667638483965014, 'Science Fiction (Alternate History) ': 0.03950437317784256, 'Young Adult': 0.03644314868804665, 'Horror': 0.034256559766763846, 'Historical (Historical Fiction) ': 0.024198250728862974, 'Adventure': 0.021720116618075803}
{'Mystery': 0.24297752808988765, 'Science Fiction (Alternate History) ': 0.18679775280898878, 'Fiction': 0.1425561797752809, 'Historical (Historical Fiction) ': 0.12570224719101122, 'Science Fiction': 0.09691011235955056, 'Fantasy': 0.07724719101123595, 'Historical': 0.05056179775280899, 'Speculative Fiction': 0.03089887640449438, 'Mystery (Crime) ': 0.02457865168539326, 'Thriller (Mystery Thriller) ': 0.021769662921348316}
{'Science Fiction (Alternate History) ': 0.4273927392739274, 'Fiction': 0.20462046204620463, 'Historical (Historical Fiction) ': 0.11716171617161716, 'Science Fiction': 0.10891089108910891, 'Fantasy': 0.037953795379537955, 'War': 0.034653465346534656, 'Military History (Civil War) ': 0.028052805280528052, 'War (Military Fiction) ': 0.0165016501650165, 'Historical': 0.013201320132013201, 'Science Fiction Fantasy': 0.01155115511551155}
{'Historical (Historical Fiction) ': 0.19187875321704317, 'Young Adult': 0.19087789533886187, 'Fantasy': 0.1731484129253646, 'Horror': 0.12610809265084358, 'Horror (Zombies) ': 0.08006863025450386, 'Historical': 0.07406348298541607, 'Fiction': 0.06519874177866743, 'Science Fiction (Alternate History) ': 0.03674578209894195, 'Audiobook': 0.03517300543322848, 'Science Fiction (Dystopia) ': 0.026737203317128967}
{'Fiction': 0.41535615171137835, 'Science Fiction': 0.13182238667900092, 'Science Fiction (Alternate History) ': 0.11563367252543941, 'Mystery': 0.06845513413506013, 'Science Fiction (Dystopia) ': 0.061517113783533764, 'Audiobook': 0.05735430157261795, 'Historical (Historical Fiction) ': 0.041628122109158186, 'Fantasy': 0.04024051803885292, 'Thriller': 0.034227567067530065, 'Race': 0.033765032377428304}
{'Fantasy': 0.5116570569064929, 'Fantasy (Dragons) ': 0.11682125846076712, 'Historical (Historical Fiction) ': 0.09927300075206819, 'Fiction': 0.0769616445224367, 'Science Fiction (Alternate History) ': 0.06192028077212334, 'Historical': 0.05314615191777388, 'Historical Fiction (Historical Fantasy) ': 0.02707445475056405, 'Science Fiction Fantasy': 0.01905239408373026, 'Adventure': 0.018049636500376033, 'War': 0.016044121333667585}
{'Science Fiction': 0.3345959595959596, 'Science Fiction (Alternate History) ': 0.3106060606060606, 'Fiction': 0.14772727272727273, 'Historical (Historical Fiction) ': 0.0707070707070707, 'War': 0.03787878787878788, 'Fantasy': 0.030303030303030304, 'War (Military Fiction) ': 0.023989898989898988, 'Science Fiction (Aliens) ': 0.016414141414141416, 'Historical': 0.015151515151515152, 'Science Fiction Fantasy': 0.012626262626262626}
{'Science Fiction (Steampunk) ': 0.2504792994455671, 'Fantasy': 0.2254002798072439, 'Romance': 0.10953935437069279, 'Fantasy (Paranormal) ': 0.09995336545935023, 'Paranormal (Vampires) ': 0.07331986113270117, 'Fantasy (Urban Fantasy) ': 0.06404476915902378, 'Fiction': 0.05492512565417897, 'Historical (Historical Fiction) ': 0.050572568526866674, 'Historical': 0.03735944867609721, 'Shapeshifters (Werewolves) ': 0.03440592776827815}
{'Historical (Historical Fiction) ': 0.31766612641815234, 'Young Adult': 0.2257467006251447, 'Fantasy': 0.14146793239175734, 'Historical': 0.09191942579300764, 'Science Fiction (Alternate History) ': 0.05255846260708497, 'Science Fiction': 0.050474646909006715, 'Fiction': 0.046538550590414444, 'Science Fiction (Dystopia) ': 0.03102570039360963, 'Adventure': 0.0231535077564251, 'War (World War II) ': 0.019448946515397084}
{'Fantasy': 0.21566632756866735, 'Historical (Historical Fiction) ': 0.14649033570701933, 'Fiction': 0.13123092573753814, 'Science Fiction (Alternate History) ': 0.11241098677517802, 'Novella': 0.1017293997965412, 'Science Fiction': 0.07884028484231943, 'Historical': 0.07019328585961343, 'LGBT': 0.052899287894201424, 'GLBT (Queer) ': 0.048830111902339775, 'Westerns': 0.04170905391658189}
{'Science Fiction (Alternate History) ': 0.4782608695652174, 'Fiction': 0.1608695652173913, 'Historical (Historical Fiction) ': 0.11304347826086956, 'Science Fiction': 0.10869565217391304, 'War': 0.043478260869565216, 'Fantasy': 0.03695652173913044, 'War (Military Fiction) ': 0.01956521739130435, 'Science Fiction Fantasy': 0.017391304347826087, 'Historical': 0.013043478260869565, 'Speculative Fiction': 0.008695652173913044}
{'Fiction': 0.1845085860431129, 'Fantasy': 0.175130921933991, 'Historical (Historical Fiction) ': 0.1741566191694069, 'Horror': 0.16112531969309463, 'Paranormal (Vampires) ': 0.11533308975764218, 'Fantasy (Paranormal) ': 0.06540007307270734, 'Historical': 0.04652295700889051, 'Fantasy (Supernatural) ': 0.03166483984898307, 'Science Fiction (Alternate History) ': 0.026062598952624527, 'Humor': 0.02009499451954695}
{'Sequential Art (Graphic Novels) ': 0.36735001507386195, 'Sequential Art (Comics) ': 0.29947995176364184, 'Fiction': 0.11610642146517938, 'Science Fiction': 0.055245703949351826, 'Fantasy': 0.04638981006933977, 'Graphic Novels Comics': 0.033840820018088635, 'Comics (Comic Book) ': 0.024193548387096774, 'Classics': 0.022083207717817306, 'Comics (Superheroes) ': 0.019822128429303587, 'Science Fiction (Dystopia) ': 0.015488393126318964}
{'Fantasy': 0.5086778163458504, 'Fantasy (Dragons) ': 0.1167560744714421, 'Historical (Historical Fiction) ': 0.0975071000315557, 'Fiction': 0.07604922688545282, 'Science Fiction (Alternate History) ': 0.06595140422846324, 'Historical': 0.050804670242978855, 'Historical Fiction (Historical Fantasy) ': 0.031555695803092455, 'Science Fiction Fantasy': 0.019880088355948247, 'Adventure': 0.01861786052382455, 'Audiobook': 0.014200063111391607}
{'Science Fiction (Alternate History) ': 0.2953216374269006, 'Science Fiction': 0.21198830409356725, 'Fiction': 0.13157894736842105, 'Fantasy': 0.10964912280701754, 'Science Fiction (Time Travel) ': 0.09649122807017543, 'Historical (Historical Fiction) ': 0.07456140350877193, 'Historical': 0.03070175438596491, 'War (Military Fiction) ': 0.021929824561403508, 'Science Fiction Fantasy': 0.014619883040935672, 'Speculative Fiction': 0.013157894736842105}
{'Science Fiction (Steampunk) ': 0.3006359606860667, 'Young Adult': 0.20639814993254962, 'Fantasy': 0.1229523993062247, 'Science Fiction': 0.09520138755058778, 'Historical (Historical Fiction) ': 0.08460204278280979, 'Fiction': 0.04875698593177876, 'Science Fiction (Alternate History) ': 0.03892850260165735, 'Adventure': 0.03623048756985932, 'Historical': 0.03584505685103103, 'Romance': 0.030449026787434958}
{'Science Fiction': 0.23645320197044334, 'Science Fiction (Alternate History) ': 0.1921182266009852, 'Fantasy': 0.15467980295566502, 'Science Fiction (Time Travel) ': 0.15369458128078817, 'Fiction': 0.13497536945812807, 'Historical (Historical Fiction) ': 0.041379310344827586, 'Science Fiction Fantasy': 0.024630541871921183, 'Historical': 0.024630541871921183, 'Audiobook': 0.019704433497536946, 'Adventure': 0.017733990147783252}
{'Science Fiction (Alternate History) ': 0.375, 'Science Fiction': 0.32884615384615384, 'Fiction': 0.125, 'Historical (Historical Fiction) ': 0.05961538461538462, 'Fantasy': 0.028846153846153848, 'War': 0.026923076923076925, 'War (Military Fiction) ': 0.021153846153846155, 'Science Fiction Fantasy': 0.015384615384615385, 'Science Fiction (Military Science Fiction) ': 0.009615384615384616, 'Novels': 0.009615384615384616}
{'Science Fiction (Alternate History) ': 0.5091863517060368, 'Fiction': 0.14698162729658792, 'Historical (Historical Fiction) ': 0.11548556430446194, 'Science Fiction': 0.09711286089238845, 'War': 0.05249343832020997, 'Fantasy': 0.03674540682414698, 'War (Military Fiction) ': 0.013123359580052493, 'Science Fiction Fantasy': 0.013123359580052493, 'War (World War I) ': 0.007874015748031496, 'Novels': 0.007874015748031496}
{'Fantasy': 0.5104921785578024, 'Fantasy (Dragons) ': 0.1198016024418161, 'Historical (Historical Fiction) ': 0.09958031285768791, 'Science Fiction (Alternate History) ': 0.06943914536436474, 'Fiction': 0.0675314765356734, 'Historical': 0.04959938954597482, 'Historical Fiction (Historical Fantasy) ': 0.03014116749332316, 'Adventure': 0.02060282334986646, 'Science Fiction Fantasy': 0.019839755818389926, 'Audiobook': 0.012972148035101107}
{'Science Fiction (Alternate History) ': 0.35714285714285715, 'Science Fiction': 0.3253968253968254, 'Fiction': 0.1388888888888889, 'Historical (Historical Fiction) ': 0.06547619047619048, 'War (Military Fiction) ': 0.027777777777777776, 'War': 0.025793650793650792, 'Fantasy': 0.025793650793650792, 'Science Fiction Fantasy': 0.013888888888888888, 'Science Fiction (Military Science Fiction) ': 0.00992063492063492, 'Historical': 0.00992063492063492}
{'Science Fiction (Alternate History) ': 0.4930747922437673, 'Fiction': 0.16066481994459833, 'Historical (Historical Fiction) ': 0.10803324099722991, 'Science Fiction': 0.09141274238227147, 'War': 0.055401662049861494, 'Fantasy': 0.036011080332409975, 'War (Military Fiction) ': 0.019390581717451522, 'Science Fiction Fantasy': 0.013850415512465374, 'War (World War I) ': 0.0110803324099723, 'Speculative Fiction': 0.0110803324099723}
{'Science Fiction (Alternate History) ': 0.4861878453038674, 'Fiction': 0.16022099447513813, 'Science Fiction': 0.10497237569060773, 'Historical (Historical Fiction) ': 0.09116022099447514, 'War': 0.04696132596685083, 'Fantasy': 0.04696132596685083, 'Historical': 0.019337016574585635, 'Science Fiction Fantasy': 0.016574585635359115, 'War (Military Fiction) ': 0.013812154696132596, 'Literature (American) ': 0.013812154696132596}
{'Historical (Historical Fiction) ': 0.3908521044292898, 'Fiction': 0.34511262657573877, 'Historical': 0.06578494179238134, 'Audiobook': 0.0409864297031067, 'Race': 0.03161810291382517, 'Literary Fiction': 0.02955156023971895, 'Cultural (African American) ': 0.028380519391058758, 'Adult': 0.023351932217400288, 'Adult Fiction': 0.0221808913687401, 'Novels': 0.0221808913687401}
{'Science Fiction (Alternate History) ': 0.36477987421383645, 'Science Fiction': 0.3228511530398323, 'Fiction': 0.1320754716981132, 'Historical (Historical Fiction) ': 0.06708595387840671, 'War': 0.029350104821802937, 'War (Military Fiction) ': 0.027253668763102725, 'Fantasy': 0.020964360587002098, 'Science Fiction Fantasy': 0.014675052410901468, 'Science Fiction (Military Science Fiction) ': 0.010482180293501049, 'Adventure': 0.010482180293501049}
{'Fantasy': 0.6322639225181598, 'Fiction': 0.1292372881355932, 'Science Fiction (Alternate History) ': 0.04963680387409201, 'Science Fiction': 0.0475181598062954, 'Historical (Historical Fiction) ': 0.0387409200968523, 'Science Fiction Fantasy': 0.03631961259079903, 'Young Adult': 0.01937046004842615, 'Historical': 0.018462469733656173, 'Fantasy (Magic) ': 0.016646489104116223, 'Speculative Fiction': 0.011803874092009685}
{'Science Fiction (Alternate History) ': 0.5597269624573379, 'Fiction': 0.14334470989761092, 'Science Fiction': 0.10921501706484642, 'Historical (Historical Fiction) ': 0.07849829351535836, 'War': 0.030716723549488054, 'Fantasy': 0.027303754266211604, 'War (Military Fiction) ': 0.017064846416382253, 'Science Fiction Fantasy': 0.013651877133105802, 'Speculative Fiction': 0.013651877133105802, 'Audiobook': 0.006825938566552901}
{'Horror': 0.2763782402336619, 'Fantasy': 0.2062796641109894, 'Paranormal (Vampires) ': 0.13946695874406717, 'Fiction': 0.09748083242059145, 'Historical (Historical Fiction) ': 0.07922599488864548, 'Science Fiction (Alternate History) ': 0.05768528660094925, 'Science Fiction (Steampunk) ': 0.054764512595837894, 'Fantasy (Paranormal) ': 0.03431909456005842, 'Historical': 0.028842643300474625, 'Mystery': 0.02555677254472435}
{'Science Fiction (Steampunk) ': 0.2906073446327684, 'Science Fiction': 0.2891949152542373, 'Fiction': 0.18785310734463276, 'Science Fiction (Alternate History) ': 0.055437853107344635, 'Science Fiction (Cyberpunk) ': 0.04943502824858757, 'Fantasy': 0.04060734463276836, 'Historical (Historical Fiction) ': 0.038135593220338986, 'Science Fiction Fantasy': 0.020480225988700564, 'Speculative Fiction': 0.01518361581920904, 'Novels': 0.013064971751412429}

In [6]:
def calculate_genre_ratios(genres_str):
    genres = ast.literal_eval(genres_str)
    
    total = sum(genres.values())
    
    if total == 0:
        return {genre: 0.0 for genre in genres}
    return {genre: f"{count / total:.2f}" for genre, count in genres.items()}
df['Genres'] = df['Genres'].apply(calculate_genre_ratios)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [7]:
df = pd.read_csv("data/scifi_books.csv")
df

,Book_Title,Original_Book_Title,Author_Name,Edition_Language,Rating_score,Rating_votes,Review_number,Book_Description,Year_published,Genres,url,Subgenre
0,The Man in the High Castle,The Man in the High Castle,Philip K. Dick,English,3.62,180593,11895,It's America in 1962. Slavery is legal once ag...,1962,"{'Science Fiction': '0.34', 'Fiction': '0.28',...",https://www.goodreads.com/book/show/216363.The...,alternate_history
1,His Majesty's Dragon,His Majesty's Dragon,Naomi Novik,English,4.03,83308,6588,Aerial combat brings a thrilling new dimension...,2006,"{'Fantasy': '0.56', 'Fantasy (Dragons) ': '0.1...",https://www.goodreads.com/book/show/28876.His_...,alternate_history
2,Leviathan,Leviathan,Scott Westerfeld,English,3.90,88293,7052,"Prince Aleksander, would-be heir to the Austro...",2009,"{'Science Fiction (Steampunk) ': '0.27', 'Youn...",https://www.goodreads.com/book/show/6050678-le...,alternate_history
3,Jonathan Strange & Mr Norrell,Jonathan Strange & Mr Norrell,Susanna Clarke,English,3.82,206919,14397,"Sophisticated, witty, and ingeniously convinci...",2004,"{'Fantasy': '0.54', 'Fiction': '0.18', 'Histor...",https://www.goodreads.com/book/show/14201.Jona...,alternate_history
4,The Yiddish Policemen's Union,The Yiddish Policemen's Union,Michael Chabon,English,3.71,70984,6992,"For sixty years, Jewish refugees and their des...",2007,"{'Fiction': '0.44', 'Mystery': '0.18', 'Scienc...",https://www.goodreads.com/book/show/16703.The_...,alternate_history
...,...,...,...,...,...,...,...,...,...,...,...,...
11090,Three Parts Dead,Three Parts Dead,Glynn James,English,4.24,2252,76,A world fallen - under a plague of seven billi...,2013,"{'Horror (Zombies) ': '0.30', 'Horror': '0.21'...",https://www.goodreads.com/book/show/16063889-t...,apocalyptic
11091,Tales of the Dying Earth,The Dying Earth / The Eyes of the Overworld / ...,Jack Vance,English,4.14,4906,382,NaN,1998,"{'Fantasy': '0.48', 'Science Fiction': '0.24',...",https://www.goodreads.com/book/show/40866.Tale...,apocalyptic
11092,The Preparation,\n 0615680682\n ...,Glen Tate,English,3.90,1015,83,"Meet Grant Matson: lawyer, father, suburbanite...",2012,"{'Fiction': '0.26', 'Adventure (Survival) ': '...",https://www.goodreads.com/book/show/15994062-t...,apocalyptic
11093,The End: Visions of Apocalypse (SFFWorld.com a...,The End: Visions of Apocalypse (SFFWorld.com a...,N.E. White,English,3.54,384,43,Everyone knows the world is going to end on De...,2012,"{'Science Fiction': '0.26', 'Short Stories': '...",https://www.goodreads.com/book/show/17156181-t...,apocalyptic
11094,The Junkie Quatrain,The Junkie Quatrain,Peter Clines,English,3.74,1501,142,Four short stories. Each one's a different typ...,2011,"{'Horror': '0.25', 'Horror (Zombies) ': '0.22'...",https://www.goodreads.com/book/show/12484914-t...,apocalyptic

In [9]:
df.insert(0, 'id', range(1001, 1001 + len(df)))

In [11]:
df.to_csv("data/scifi_books.csv", index=False)

In [ ]:
df = pd.read_csv("data/scifi_books.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'books.csv'